development:
  adapter: postgresql
  port: 5432
  database: development
  username: postgres
  password: postgres

test:
  adapter: postgresql
  port: 5432
  database: test
  username: postgres
  password: postgres

production:
  adapter: postgresql
  port: 5432
  database: production
  username: postgres
  password: postgres
